### PR TITLE
init script could be usefull ?

### PR DESCRIPTION
**Pull request by johnydevops**
Init job benefits:
-**Mumbledj runs on each boot**
-**Automatically start the process**  with `respawn` variable
```
*respawn*
A service or task with this stanza will be automatically started if it should stop abnormally. All reasons for a service stopping, except the stop(8) command itself, are considered abnormal. Tasks may exit with a zero exit status to prevent being respawned.
*respawn limit COUNT INTERVAL*
Respawning is subject to a limit, if the job is respawned more than COUNT times in INTERVAL seconds, it will be considered to be having deeper problems and will be stopped. Default COUNT is 10. Default INTERVAL is 5 seconds.
```
-**Easy to stop and start mumbledj in background**

`# stop mumbledj`

`# start mumbledj`

I am using it and I find very useful.

### CODE REVIEW

**Comment by matthieugrieger** [comment]
Thanks for the PR. I'm not sure if this would be appropriate to include in the repo due to different requirements for each user's environment and needs. I think it might be useful to include an example like the one you have provided in the README though. Maybe that would be better?

For what it's worth, I also run a similar upstart script on my own server, but there are a few minor differences.

**Comment by raz0rsdge** [comment]
It could be a problem for ppl like me, using mumbleDJ in multiuser environments with no root access.

**Comment by matthieugrieger** [comment]
Closing due to possible incompatibilities with particular environments. I may add an example of something like this to the README at some point, though.

**Comment by RushNY** [comment]
Just want to add that on my Ubuntu droplet it wasn't starting properly at boot because the network wasn't up yet, start on net-device-up IFACE=eth0 fixed that.

**Pull request closed without merging**
