### PR TITLE
Supports adding youtube playlist with more than 50 items

### PR DESCRIPTION
**Pull request by GabrielPlassard**
Playlist with more than 50 elements will have all their items added to the songqueue.

### CODE REVIEW

**Comment by matthieugrieger** [comment]
Looks pretty good, just one comment though. Since this opens up the possibility for people to add huge playlists, maybe it would be a good idea to add a configuration variable for the maximum amount of items to add to a playlist? Should be an easy addition.

**Comment by GabrielPlassard** [comment]
I've added the MaxSongPerPlaylist option as you suggested, I used 50 as default value since it's the current configuration.

I'm not so sure how passing arrays by value or copy works in go. I tried to use a pointer but I couldn't make it work.

**Comment by matthieugrieger** [comment]
I think an easier way to approach this would be to initialize a counter to 0 before reading the pages, and then increment the counter as new songs are added to the queue. Once the counter hits the max number of songs in a playlist the function could break out of the loop.

[Here is where we could increment the counter, after the append statement.](https://github.com/GabrielPlassard/mumbledj/blob/support_playlists_over_50_songs/service_youtube.go#L169-L175)

The other drawback of the current approach is that we are performing API calls to retrieve metadata about YouTube videos that may never get added to the queue.

**Comment by GabrielPlassard** [comment]
I modified as you suggested, except I used len(songArray) instead of an additional variable.

**Comment by matthieugrieger** [comment]
Awesome, that should work!

One last thing, I promise: for consistency we should probably add this to the SoundCloud playlists as well. [Here is the relevant piece of code](https://github.com/matthieugrieger/mumbledj/blob/master/service_soundcloud.go#L70-L74). I think the implementation would be almost exactly the same.

**Comment by GabrielPlassard** [comment]
Should be ok!

**Comment by matthieugrieger** [comment]
Looks good, thanks again. :)

**Pull request merged**
