### PR TITLE
Soundcloud integration

### PR DESCRIPTION
**Pull request by MichaelOultram**
Adds soundcloud integration for mumbledj as per the feature request #47. A soundcloud key would need to be generated from http://soundcloud.com/you/apps/new and added into the environment variable `SOUNDCLOUD_API_KEY`. I tried to write the code with the intention of making it easier to add support for other platforms, which is why some of the original code got moved around. Oh, and sorry about all the commits, I have no way of compiling it on my Windows desktop, and use git to put it on my ubuntu server

### CODE REVIEW

**Comment by matthieugrieger** [comment]
Hey there!

Thanks for doing this. I will take a look at it soon (move-in day at university).

One thing -- do you think you could squash the commits into   1-10 commits? That way it won't fill up the git history as much.

Thanks again!

**Comment by MichaelOultram** [comment]
I'll look into it, git still confuses me sometimes

**Comment by MichaelOultram** [comment]
I think I've made it worse. *Sigh* Why does git never do what I want?

**Comment by matthieugrieger** [comment]
No worries. I'll take a look when I get a chance.

**Comment by matthieugrieger** [comment]
Actually, don't worry about it. I think I can squash the commits myself when I merge it. I will hopefully get to it soon.

**Comment by matthieugrieger** [comment]
Alright, just took a look through the code. Looks good! You made some simplifications that I was planning to do during the refactor. :)

One suggestion: Maybe we should rename the types in `youtube-dl.go` to something like `AudioTrack` and `AudioPlaylist`? Right now Soundcloud tracks are being added as YouTube songs here: https://github.com/MichaelOultram/mumbledj/blob/master/service_soundcloud.go#L111

I'm sure it works, might just be a little misleading.

P.S. I like what you did with the thumbnails for Soundcloud!

**Comment by MichaelOultram** [comment]
Good point, made that change

**Comment by matthieugrieger** [comment]
Thanks, I'll get to work on merging soon.

**Comment by matthieugrieger** [comment]
I did some testing and it works great! Your changes have been merged. Thanks again. :)

**Pull request closed without merging**
