### PR TITLE
Store song cache in XDG_CACHE_HOME

### PR DESCRIPTION
**Pull request by yrro**

### CODE REVIEW

**Comment by matthieugrieger** [comment]
Cool, thanks! This definitely seems to be a better practice than what is being used currently.

I searched a little to find the answer to this, but couldn't seem to find a clear answer: what happens if the `XDG_CACHE_HOME` environment variable isn't defined? Or is this something that can be safely assumed to be defined on any reasonable distro?

**Comment by yrro** [comment]
Just fixed a few silly mistakes that I should have noticed before raising the original pull request.

If `XDG_CACHE_HOME` is not defined then `~/.cache` is used instead, so the default cache location becomes `~/.cache/mumbledj/songs`.

**Comment by yrro** [comment]
BTW, there's also an `XDG_CONFIG_HOME` which defaults to `~/.config`; it also has a (default but changeable) search path, so the config would be loaded from the first that exists out of `~/.config/mumbledj/mumbledj.gcfg`, `/etc/xdg/mumbledj/mumbledj.gcfg` would be used. I didn't do this since I saw in another bug report that you were thinking about refactoring the config code anyway.

**Comment by matthieugrieger** [comment]
Sounds like a good idea. For the refactor I was planning on making the config file optional and passed in via commandline argument, but maybe having a pre-generated configuration file in `XDG_CONFIG_HOME` would be a better way to handle that.

**Comment by matthieugrieger** [comment]
Closing this issue as it is being addressed in the refactor I am working on.

**Pull request closed without merging**
