### PR TITLE
Added a restriction on maximum video length

### PR DESCRIPTION
**Pull request by jakexks**
For some reason, people think submitting 10 hour videos to the queue is funny :laughing:

### CODE REVIEW

**Comment by jakexks** [comment]
I've never used go, so I assume the way I've handled error checking is bad. Let me know if there's a more sane way!

**Comment by matthieugrieger** [comment]
Thanks for the PR! Looks pretty good. However, I think that with this approach people could still add songs over the limit if they are contained in a playlist.

I think that if a song in a playlist is over the limit, a message should not be output. There would potentially be cases where the chat would be spammed.

Also I'd like to keep the functionality the same as it is currently by default (i.e. no time limit), so maybe add a boolean config option to enable/disable song length checking, with it being false by default?

**Comment by mkody** [comment]
> Also I'd like to keep the functionality the same as it is currently by default (i.e. no time limit), so maybe add a boolean config option to enable/disable song length checking, with it being false by default?

Or put the value at `0` (default) to disable it?

**Comment by matthieugrieger** [comment]
> Or put the value at 0 (default) to disable it?

Even better!

**Comment by jakexks** [comment]
The default max length is now 0 (disabled)

**Comment by jakexks** [comment]
Hmm, it panics when I add a playlist where all songs are rejected: 
```
panic: runtime error: index out of range

goroutine 20 [running]:
runtime.panic(0x789320, 0xbd5c3c)
        /usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
main.add(0xc2080eae70, 0xc208035b60, 0x7, 0xc20803ee05, 0x38)
        /mumbledj/commands.go:200 +0xb8f
main.parseCommand(0xc2080eae70, 0xc208035b60, 0x7, 0xc20803ee01, 0x3c)
        /mumbledj/commands.go:38 +0x264
main.(*mumbledj).OnTextMessage(0xbedfa0, 0xc2080fafc0)
        /mumbledj/main.go:78 +0x13d
main.*mumbledj.OnTextMessage·fm(0xc2080fafc0)
        /mumbledj/main.go:162 +0x30
```
I assume this is because it tries to play an empty queue

**Comment by matthieugrieger** [comment]
Yeah, I think you're right. I think if you just change [this line](https://github.com/matthieugrieger/mumbledj/blob/master/commands.go#L197) to the following it should fix that problem:

`if oldLength == 0 && dj.queue.Len() != 0 && !dj.audioStream.IsPlaying() {`

**Comment by jakexks** [comment]
OK, tested working using. https://www.youtube.com/playlist?list=PL3643A06A0085A400

**Comment by matthieugrieger** [comment]
Sweet! I will take a look at the PR as a whole and merge it as soon as
possible. Thanks for all the work!

One of my friends actually added a 10 hour song last night, so it looks
like I need this feature too. :)

**Pull request merged**
