### PR TITLE
Added listsongs command

### PR DESCRIPTION
**Pull request by nkhoit**
Added a command to list the songs in the queue.

### CODE REVIEW

**Comment by matthieugrieger** [comment]
Thanks for the PR! This is a good idea.

At first glance everything looks okay. I will test it as soon as I can and then merge it if everything works fine!

**Comment by matthieugrieger** [comment]
Works great! Thanks again. :)

**Comment by nkhoit** [comment]
I guess the only thing is after 74 songs in the queue, you get a [[ Text object too large to display ]] error from mumble.
I don't think there's anything that can be done from here right?

**Comment by matthieugrieger** [comment]
Nice catch! Does it always happen at 74 songs? I would expect that this is a limitation of the Mumble protocol and not an issue with your code.

If it is a Mumble protocol thing, then it might be wise to check the length of strings before they are sent to the server so that a more clear error message could be output instead.

**Comment by GabrielPlassard** [comment]
First of all, thank you very much for this feature!

There is a configuration entry 'textmessagelength' in the mumble-server.ini file, which should be accessible by the client

https://wiki.mumble.info/wiki/Murmur.ini#textmessagelength

https://raw.githubusercontent.com/mumble-voip/mumble/master/src/Mumble.proto -> ServerConfig.message_length

**Comment by matthieugrieger** [comment]
Thanks @GabrielPlassard! I will look into this some more.

**Comment by nkhoit** [comment]
I tried specifying textmsssagelength=0 in my mumble-server.ini but I still get this error.
I looked into it more and it's a client-side error. 
https://github.com/mumble-voip/mumble/blob/master/src/mumble/Log.cpp#L451
Seems to be dependent on the client's screen resolution. So this is pretty comical because I have a different limit on !listsongs depending on which monitor I have Mumble on.
This seems pretty strange because basically, no matter the size of the actual mumble window, it limits the size of the text message to the vertical and horizontal sizes of your screen...

Since there's probably no way for us to figure out this client size limit. The best might be to add an optional argument to list the first x songs? ex: !listsongs 10 will list the next 10 songs.

**Comment by GabrielPlassard** [comment]
I think there are 2 issues then
* the bot sending a message which is too long for the server (which I also solved by setting textmsssagelength=0)
* the [[ Text object too large to display ]], which is due to the client

I think the first one is still problematic, since there is no error message explaining what went wrong (you send !listsongs, the bot doesn't seem to respond and nothing is logged).

The second one seems more complicated, and your solution seems like a good compromise to me.

**Comment by nkhoit** [comment]
Okay, I'll give a shot at fixing that first issue tonight. If it gets an error message back from the server saying the textmessage is too long it'll send some feedback.

**Comment by matthieugrieger** [comment]
@nkhoit: Wow, I never would have guessed that it was based on your screen resolution! That's pretty funny.

I like your solution with the optional argument. I think that's the best way to go.

**Comment by nkhoit** [comment]
I added the argument for listsongs. 

I looked at solving the first issue @GabrielPlassard noted.
Not sure what's the right way to do this? 
mumbledj.SendPrivateMessage calls gumble.User.Send
But Send doesn't return anything about if it failed or not? https://github.com/layeh/gumble/blob/master/gumble/user.go#L208

Is there any other way or is this something that needs to be added in gumble?

**Comment by matthieugrieger** [comment]
@bontibon: Do you know of a good way to solve this issue? I noticed that the `Send` method for `Client` returns an error but the `Send` method for `User` does not. Is there a reason for this?

`Client.Send()`: https://github.com/layeh/gumble/blob/master/gumble/client.go#L240-L243
`User.Send()`: https://github.com/layeh/gumble/blob/master/gumble/user.go#L207-L214

Also, is there any easy way to access the current value of `textmessagelength` in the Mumble config?

**Comment by bontibon** [comment]
> I noticed that the Send method for Client returns an error but the Send method for User does not. Is there a reason for this?

No reason. `Client.Send` only returns socket write errors that occur; never any permission errors, etc. I suppose `User.Send` could pass along the error returned from `Client.Send`. However, thinking about it now, I may actually remove the return value from `Client.Send`. If an error happens, the `OnDisconnect` handler should be called very soon after.

> Do you know of a good way to solve this issue?

The easiest thing to do would be to split the list into separate text messages. Example:

```go
var buffer bytes.Buffer
dj.queue.Traverse(func(i int, song Song) {
    buffer.WriteString(fmt.Sprintf(SONG_LIST_HTML, song.Title(), song.Submitter()))
    if i % 20 == 0 && i > 0 {
        dj.SendPrivateMessage(user, buffer.String())
        buffer.Reset()
    }
})
if buffer.Len() > 0 {
    dj.SendPrivateMessage(user, buffer.String())
}
```

> is there any easy way to access the current value of textmessagelength in the Mumble config?

You can get this information from inside of the `OnServerConfig` event handler.

**Pull request merged**
