### PR TITLE
Make playlistItems a config option

### PR DESCRIPTION
**Pull request by hamilton5**
Instead of the default 25 songs per playlist make it configurable.

### CODE REVIEW

**Comment by matthieugrieger** [comment]
Good idea! I will take a look at this later.

**Comment by matthieugrieger** [comment]
@hamilton5: Okay, I got a chance to look at the PR. Some things that should probably be changed before I pull it in:

**1)** There should be some sort of check to make sure that the value entered into the config file is between 1 and 25 (inclusive). If it is not within the range, the limit should be set to 25.

**2)** I feel that the `maxresults` variable should be left in the URL string. It can just be set to the new config value via `fmt.Sprintf`, much like how I did it with the `id`.

Other than those two things, it looks good. Thanks for the PR!

**Comment by hamilton5** [comment]
1) I figure it's going to crash like any other config option not being set right (ie SkipRatio = a) - What if a user wants more then 25, my limit is 100 for example.

2) I entered that URL in browser and did not see any change from 25 to 10 to nothing. I did not think it was functional.

only my 2nd PR ever - thought I'd try. Ill keep the patch for myself :+1:

**Comment by matthieugrieger** [comment]
There are two potential problems with the way the config value is set up at the moment that I see:
**1)** Setting the config value to 0.
**2)** Setting the config value to something over 25.

The reason why it is problematic to use a number over 25 is because (at least when I tested it) YouTube only gives back YouTube videos in groups of 25 in their JSON responses if there are more than 25 videos in a playlist. It *can* be rewritten to support more than 25 videos, but I didn't think it was worth the extra hassle.

No worries if you don't want to merge it then. Just be sure to close the pull request if that is what you want.

**Comment by hamilton5** [comment]
Thank you for the heads up. This is what happens when diving head first not knowing everything. Will close and thanks again for this project!.

**Comment by matthieugrieger** [comment]
No worries! Glad you like it!

**Pull request closed without merging**
